[build]
target = "riscv32imfc-unknown-none-elf.json"

[unstable]
build-std = ["core"]
json-target-spec = true

[env]
#DEFMT_LOG = "debug"
DEFMT_LOG = "error"

[target.riscv32imfc-unknown-none-elf]
runner = "probe-rs run --chip CH32V307VCT6 --rtt-channel-mode no-block-skip"
